const cn={
  message: {
    hello: '你好',
  },
  contactUs:{
    title:'联系我们',
    type :'标注 (采集)类型:',
    typerules :'请至少选择一个类型',
    typename0:'大模型',
    typename1:'图片',
    typename2:'3D',
    typename3:'文本',
    typename4:'语音',
    typename5:'视频',
    typename6:'其他',
    description:'需求说明',
    descriptionplaceholder:'请提供您的需求，我们会尽快与您联系。(选填，最多500字符)',
    company:'公司名称:',
    companyplaceholder:'请输入公司名称',
    name:'姓名:',
    nameplaceholder:'请输入姓名',
    phone:'联系方式:',
    phoneplaceholder:'请输入移动电话',
    email:'邮箱:',
    emailplaceholder:'请输入电子邮箱',
    uploadfile:'上传',
    uploadfiletitle:'上传文件',
    uploadfileplaceholder:'如果您有更详细的需求说明，请直接上传',
    elMessage:'信息提交成功，请稍候！',
    confirm:'提交',
    cancel:'取消',
  },
  features:{
    title1:"多样标注任务",
	content1:"各模态数据标注 各领域数据标注",
	title2:"丰富的标注经验",
	content2:"专业培训标注员 一对一精准派单",
	title3:"严格质量管理",
	content3:"人工多轮质检 算法工程师指导修正",
	title4:"自研标注平台",
	content4:"数据防泄漏 大任务合作效率高",
	title5:"文本数据标注",
	content5:"文本分类",
	content6:"实体抽取",
	content7:"关系判定",
	content8:"事件标注",
	content9:"问答标注",
	content10:"文本清洗",
	content11:"OCR转写",
	content12:"情感标注",
	content13:"文本摘要",
	content14:"词性标注",
	content15:"标签抽取",
	content16:"搜索相关性",
	content17:"意图判断",
	content18:"平行语料构建",
	content19:"阅读理解",
	content20:"文本改错",
	content21:"分词标注",
	content22:"知识图谱构建",
	title6:"图像数据标注",
	content23:"图像分类",
	content24:"目标检测",
	content25:"语义分割",
	content26:"实例分割",
	content27:"3D影像分割",
	content28:"关键点拾取",
	content29:"目标计数",
	title7:"视频数据标注",
	content30:"视频分类",
	content31:"关键帧抽取",
	content32:"视频打点",
	content33:"目标追踪",
	content34:"字幕对齐",
	title8:"语音数据标注",
	content35:"语音清洗",
	content36:"语音转写",
	content37:"声纹标定",
	content38:"情绪判定",
	content39:"语音切割",
	content40:"发音校对",
	content41:"因素标定",
	content42:"韵律标定"	
  },
  develop:{
	title:'随着嵌入式系统和物联网不断发展，智能电子产品也呈现出日新月异的发展势头， 电子产品制造商之间的竞争变得更加激烈与残酷。他们在软件系统设计与开发方面的技术、 人才需求越来越高。新航途提供了较高层次的专业技术支持，从需求分析、系统设计直至开发 实施、产品交付，我们都能出色的完成。我们甚至会站在客户的角度去为产品的创新出谋划策。',
	title1:"嵌入式系统开发与维护",
	content1:"基于Linux、Android等智能系统平台，运用JAVA、C/C++等语言开发工具，提供电子产品嵌入式软件系统的开发与维护。",
	title2:"智能硬件APP开发",
	content2:"集场景与设备控制为一体，适配多种智能终端，提供交互设计，UI设计，H5页面制作， 移动端开发（IOS，Android，H5）APP硬件联调等技术实施服务。",
	title3:"共享软件系统开发",
	content3:"新航途，拥有共享单车、电动车、共享货柜、共享健身等数十个共享类成功案例，可定制开发所有的共享类项目，对传统的硬件设备进行改造，使其具有共享的功能。",
	title4:"智能语音系统",
	content4:"智能语音系统主要针对于语音清洗、语音转写、声纹标定，情绪判定，语音切割，发音校对，因素标定，韵律标定等。",
	title5:"专业技术团队",
	content5:"100余人开发团队，平均5年以上开发经验，曾经均就职于大型互联网公司",
	title6:"多行业案例",
	content6:"6年开发服务，600+真实案例积累，成熟的解决方案，品质保障",
	title7:"高品质定制",
	content7:"20多主流行业的深度研究与服务经验，你想要的定制我们都能提供",
	title8:"性价比更高",
	content8:"多年的定制服务经验，开发流程更具效率，做到行业性价比更高",
	title9:"快速的周期",
	content9:"规范高效的设计、开发、测试流程，严格控制项目进度，上线周期更短",
	title10:"优质的服务",
	content10:"运营培训、上线维护、软著申请、渠道发布，还能提供更多售后服务"
  }
}

export default cn